### ISSUE TITLE
Colorize stack plot per month

### ISSUE THREAD

**Issue by Moeriki** [erikbern/git-of-theseus#10]
Would that be an option I could easily configure?

**Comment by erikbern** [comment]
you can run analyze.py with `--cohortfm %Y-%m`

**Comment by MateuszStefek** [comment]
In my project, when I run `git-of-theseus-analyze  . --cohortfm %Y-%m`, I only end up with two cohorts: "Code added in 2019-01" and "Code added in 2019-02".
This project started in January and we have been adding code all the time. I think everything younger than February is classified as "2019-02", otherwise the chart looks OK.

Do you have an idea what might be the problem?

**Comment by erikbern** [comment]
weird, no idea. if you track down the issue, let me know!
