### ISSUE TITLE
Survival going up

### ISSUE THREAD

**Issue by remram44** [erikbern/git-of-theseus#16]
I ran survival_plot.py over ReproZip's 1.0.x branch and got this:

![survival_plot](https://cloud.githubusercontent.com/assets/426784/20993176/88138614-bcb6-11e6-9cd4-e96482acfefc.png)

I imagine the graph going back up might be caused by duplication? (there are several packages in the repository which share some code) It's still surprising 😅

**Comment by erikbern** [comment]
It's because both the numerator and the denominator changes over time. Both of them go to zero. In your case there are only so many commits that reached 2.5 years old versus a lot more commits reached 1 year of age. Hope this explanation makes sense

**Comment by remram44** [comment]
No, I can't wrap my head around this 😕

Is the X axis project time or commit age?

**Comment by erikbern** [comment]
X axis is commit age

**Comment by erikbern** [comment]
here's a scenario. project has two commits, one from 2000, one from 2015. today is 2016. the first commit is still present in the code base, the second one was reverted in 2016.

first year: 100% because both commits were in the code base
second year: 50% because the second commit was removed
third year: 100% because now only the first year counts

**Comment by remram44** [comment]
I see! `(commits that age still present)/(commits that age)`, it makes sense. Thanks for explaining!

**Comment by erikbern** [comment]
you got it :)
